### ISSUE TITLE
Move XBOX sign on/off automatons into one automation

### ISSUE THREAD

**Issue by sinker1345** [sinker1345/Home-Assistant-Configuration#1]
current code for automatons are included below.

```
- alias: Is XXX on Xbox
    trigger:
     - platform: state
       entity_id: sensor.XBOXSENSOR
       from: 'Offline'
       to: 'Online'
    action:
      - service: notify.google_push
        data_template:
          message: "XXX has signed on to XBox"
          target: ["TARGET1", "TARGET2"]
          data:
           tag: 'XXX Signed on to Xbox'

  - alias: Is XXX off Xbox
    trigger:
     - platform: state
       entity_id: sensor.XBOXONESENSOR
       from: 'Online'
       to: 'Offline'
    action:
      - service: notify.google_push
        data_template:
          message: "XXX has signed off of XBox"
          target: ["TARGET1", "TARGET2"]
          data:
           tag: 'XXX Signed off of Xbox'
```
Proposed code below

```
  - alias: Is XXX on XBOX
    trigger:
     - platform: state
       entity_id: sensor.[XBOXSENSORNAME]
    action:
      - service_template: >-
         {% if trigger.to_state.state == "Online" and trigger.from_state.state == "Offline" %}
            notify.google_push
              data_template:
                message: "XXX has signed on to XBox"
                target: ["TARGET1", "TARGET2"]
                data:
                  tag: 'XXX Signed on to Xbox'
         {% elif trigger.to_state.state == "Offline" and trigger.from_state.state == "Online" %}
            notify.google_push
              data_template:
                message: "Lexi has signed off of XBox"
                target: ["TARGET1", "TARGET2"]
                data:
                  tag: 'XXX Signed off of Xbox'
         {% endif %}


  - alias: Is XXX on XBOX
    trigger:
     - platform: state
       entity_id: sensor.[XBOXSENSORNAME]
    action:
     - service_template: >-
      {% if trigger.to_state.state == "Online" and trigger.from_state.state == "Offline" %}
          notify.google_push
            {
              "title": "xxx has signed on to XBOX",
              "message": "xxx has signed on to XBOX",
              "data": {
                "tag": "xxx has signed onto XBOX"
               }
             }
      {% elif trigger.to_state.state == "Offline" and trigger.from_state.state == "Online" %}
          notify.google_push
            {
              "title": "XXX has signed off of XBOX",
              "message": "XXX has signed off of XBOX",
              "data": {
                "tag": "XXX has signed off of XBOX"
               }
             }
      {% endif %}
```

Code needs to be tested at a time that the XBOX and TV is available for testing
